### ISSUE TITLE
собрать релиз bitrix24-php-sdk v2.0-alpha.7

### ISSUE THREAD

**Issue by mesilov** [mesilov/bitrix24-php-sdk#273]
**Разработка**

- [x] ✅  унификация batch-операций #268 
- [x] ✅ #280
- [x] ✅ #282
- [x] ✅ #283
- [x] ✅ #285
- [x] ✅ #274
- [x] ✅ #275
- [x] ✅ https://github.com/mesilov/bitrix24-php-sdk/issues/292 #292
- [x] ✅ fix bug UnknownScopeCodeException - in refresh token response #295 
- [x] ✅ add application level events ONAPPINSTALL and ONAPPUNINSTALL #296
- [x] ✅ add boosty.to #301
- [x] ✅ add event «portal renamed» #250
- [x] ✅ add read models for activity #300
- [x] ✅ add telephony scope #291
- [x] ✅ support operating field #289 
- [x] ✅ add events support for telephony #304
- [x] ✅ add support im open lines scope #302
- [x] ✅ fix inconsistency method names and unnecessary dto #303

**Релиз**
- [x] cобрать все текущие изменения в ветку 273-alpha-7
- [x] написать релизноты в виде развёрнутой доки
- [x] провести релиз
- [x] отписаться в телегу
- [x] отписаться на cp
- [x] отписаться на dev
