### ISSUE TITLE
publish release bitrix24-php-sdk beta 1

### ISSUE THREAD

**Issue by mesilov** [mesilov/bitrix24-php-sdk#306]
**Bugfix**
- [x] (2.0-alpha-7) Undefined index: "operating" в Core Response #310
- [x] Undefined index: namelookup_time_us #307
- [x] Ошибка в деструкторе Response после обновления на alpha 6 #277
- [x] https://github.com/mesilov/bitrix24-php-sdk/issues/320 
- [x] fix Bitrix24\SDK\Application\Contracts #326
- [x] add auth node in telephony voximplant events requests #331
- [x] #332
**added**
- [x] add in GitHub CI support Windows platforms #360 
- [x] #324
- [ ] migrate from ramsey Uuid to Symfony Uid
- [ ] add error handlers #272
- [ ] add support for envents #293
- [x] add x-request-id support for debug rest-api queries #354
- [ ] add auth_connector support #216
- [x] Add contracts for bitrix24 account for doctrine #311
- [x] fix return types in DealCategoryItemResult #322
- [x] add Bitrix24ServiceBuilderFactory #328
- [ ] Поддержка смарт процессов (сервисы), методы crm.item.* #330
- [x] #335
- [x] #338
- [x] add scope user #339
- [ ] add support for operating timing #340
- [ ] #364

**Documentation**
- [ ] Исправить README.MD #299
